name: dotnet build

on:
  push:
  schedule:
    - cron: '* */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: configuração ambiente .net core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.301

    - name: executar script personalizado
      run: |
        printf '"Hello world!\n"'

    - name: instalar dependências 
      working-directory: .\github-actions-dotnet-webapp\github4women\github4women.csproj
      run: |
        dotnet restore 

    - name: compilação
      working-directory: .\github-actions-dotnet-webapp\github4women\github4women.csproj
      run: |
        dotnet build 

    - name: teste
      working-directory: .\github-actions-dotnet-webapp\github4women\github4women.csproj
      run: |
        dotnet test 

    - name: publicação
      working-directory: .\github-actions-dotnet-webapp\github4women\github4women.csproj
      run: |
        dotnet publish 
