name: dotnet build

on:
  push:
  schedule:
    - cron: '* */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: configuração ambiente .net core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.301

    - name: executar script personalizado
      run: |
        printf '"Hello world!\n"'

    - name: instalar dependências 
      run: |
        cd C:\Users\Letic\OneDrive\Documentos\github-actions-dotnet-webapp\github4women\github4women.csproj
        dotnet restore

    - name: compilação
      run: |
        cd C:\Users\Letic\OneDrive\Documentos\github-actions-dotnet-webapp\github4women\github4women.csproj
        dotnet build

    - name: teste
      run: |
        cd C:\Users\Letic\OneDrive\Documentos\github-actions-dotnet-webapp\github4women\github4women.csproj
        dotnet test

    - name: publicação
      run: |
        cd C:\Users\Letic\OneDrive\Documentos\github-actions-dotnet-webapp\github4women\github4women.csproj
        dotnet publish
